replicaCount: 1

containers:
  name: linux-robot

image:
  repository: registry.uipath.com/
  name: robot/uiautomation-runtime
  tag: 	23.10.69.35238-robot23.10.0
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

orchestrator:
  url: https://cloud.uipath.com/wellswemvqiy/DefaultTenant/orchestrator_
  clientId: 02600fdb-adbc-41b7-bb2e-70aa023d35cd
  clientSecret: 40EZfLfP1KwhIF05

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

